Repository hamdielzard/Wordeo, pull requests merged in 2023-10, with the labels that each got.

#50 Create database schema
  server/.env
  server/README.md
  server/__tests__/test.js
  server/models/accounts.js
  server/models/scores.js
  server/models/words.js
  server/package-lock.json
  server/package.json
  server/routes/accounts.js
  server/routes/scores.js
  server/routes/words.js
  server/server.js
Labels: developer task

#54 Finalize design and setup React
  README.md
  client/.gitignore
  client/README.md
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/robots.txt
  client/src/App.css
  client/src/App.js
  client/src/App.test.js
  client/src/index.css
  client/src/index.js
  client/src/logo.svg
  client/src/reportWebVitals.js
  client/src/setupTests.js
  images/WordeoLogo.png
  images/design/DESIGN.md
  images/design/accountmg.png
  images/design/homepage.png
  images/design/login.png
  images/design/loop1.png
  images/design/loop2.png
  images/design/loop3.png
  images/design/loop4.png
  images/wordeo_arch_v2.png
Labels: developer task

#53 Create node.js.yml
  .github/workflows/node.js.yml
Labels: developer task

#63 Create home page
  client/public/index.html
  client/public/manifest.json
  client/public/robots.txt
  client/src/App.css
  client/src/App.js
  client/src/Components/Button.js
  client/src/Pages/Account.js
  client/src/Pages/Game.js
  client/src/Pages/Home.js
  client/src/Pages/SignIn.js
  client/src/Styles/Button.css
  client/src/Styles/Home.css
  client/src/index.js
  client/src/logo.svg
Labels: high priority, developer task, frontend

#65 Add documentation for button
  client/src/Components/Button.js
  client/src/DOCUMENTATION.md
Labels: low priority, frontend

#66 add sign in page UI
  client/src/App.js
  client/src/Images/WordeoLogo.png
  client/src/Pages/SignIn.js
  client/src/Styles/General.css
  client/src/Styles/SignIn.css
Labels: high priority, frontend

#67 Add UI and stub functionality to account page
  client/src/Components/Achievement.js
  client/src/Images/trophy.png
  client/src/Pages/Account.js
  client/src/Styles/Account.css
  client/src/Styles/General.css
Labels: high priority, frontend

#71 Add word data
  client/src/App.test.js
  client/src/Pages/Home.js
  client/src/Tests/Home.test.js
  data/README.md
  data/manage.py
  data/words.json
Labels: data

#70 Add scores endpoints
  server/README.md
  server/__tests__/auth.test.js
  server/__tests__/scores.test.js
  server/__tests__/words.test.js
  server/controllers/AuthController.js
  server/documents/api.md
  server/models/accounts.js
  server/models/scores.js
  server/routes/accounts.js
  server/routes/scores.js
  server/server.js
Labels: medium priority, backend

#81 Integrate frontend to backend
  .gitignore
  client/package-lock.json
  client/package.json
  client/src/Components/Game/CoreGame.js
  client/src/Components/Game/GameOver.js
  client/src/Components/Game/IncorrectLetterBox.js
  client/src/Components/Game/Timer.js
  client/src/Pages/Account.js
  client/src/Pages/Game.js
  client/src/Pages/Home.js
  client/src/Pages/SignIn.js
  client/src/Styles/Game.css
  client/src/Styles/SignIn.css
  client/src/Styles/Timer.css
  client/src/Tests/Account.test.js
  client/src/Tests/Game.test.js
  client/src/Tests/NotFound.test.js
  client/src/Tests/SignIn.test.js
  client/src/Util/ApiCalls.js
  client/src/Util/GameModes.js
  server/__tests__/auth.test.js
  server/__tests__/test.js
  server/controllers/AuthController.js
  server/controllers/UserController.js
  server/documents/api.md
  server/index.js
  server/logger.js
  server/models/user.js
  server/package.json
  server/routes/scores.js
  server/routes/words.js
  server/server.js
Labels: high priority, integration

#101 Update job script for publish
  .github/workflows/publish-docker.yml
  docker-compose.yml
Labels: Ops

#102 update build to take release tag
  .github/workflows/publish-docker.yml
Labels: Ops

#106 Backend update
  client/src/Components/Achievement.js
  client/src/Components/Button.js
  client/src/Pages/Account.js
  client/src/Pages/Home.js
  client/src/Pages/NotFound.js
  client/src/Pages/SignIn.js
  client/src/Styles/Account.css
  client/src/Styles/Button.css
  client/src/Styles/Home.css
  client/src/Styles/SignIn.css
  client/src/Tests/Account.test.js
  server/__tests__/api.test.js
  server/__tests__/auth.test.js
  server/__tests__/scores.test.js
  server/__tests__/user.test.js
  server/controllers/AuthController.js
  server/controllers/UserController.js
  server/documents/api.md
  server/logger.js
  server/models/scores.js
  server/models/user.js
  server/routes/scores.js
  server/routes/user.js
  server/server.js
Labels: backend
