Repository hamdielzard/Wordeo, pull requests merged in 2023-11, with the labels that each got.

#127 Store backend calls
  client/src/Components/Store/ImageDisplay.js
  client/src/Components/Store/SuccessPopup.js
  client/src/Pages/Store.js
  server/models/store.js
Labels: integration

#129 Backend integration for achievements
  client/src/Pages/Account.js
  server/__tests__/user.test.js
  server/controllers/AuthController.js
  server/controllers/UserController.js
  server/models/user.js
Labels: backend, integration

#150 Update appearance
  client/src/Components/Store/Currency.jsx
  client/src/Components/Store/ItemPopup.jsx
  client/src/Pages/Account.jsx
  client/src/Pages/Leaderboard.jsx
  client/src/Pages/SignIn.jsx
  client/src/Styles/Home.css
  client/src/Styles/Leaderboard.css
  client/src/Styles/SignIn.css
  client/src/Styles/Store.css
Labels: frontend

#154 Update to earn coins at the end of the game
  client/src/Components/OldGame/GameOver.jsx
  client/src/Pages/Game.jsx
  client/src/Tests/Currency.acceptance.test.js
  client/src/Util/ApiCalls.js
Labels: frontend
